version: "3.0"

services:
  nginx:
    image: nginx
    ports:
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./localhost.key:/etc/ssl/private/localhost.key
      - ./localhost.crt:/etc/ssl/certs/localhost.crt
    depends_on:
      -  app
  app:
    build: .
    expose:
      -  8000